### ISSUE TITLE
Update to newer OpenCV versions (>=3.0.0)

### ISSUE THREAD

**Issue by okbalefthanded** [LukeAllen/optimeyes#3]
Starting from OpenCV 3, the non-free algorithms (patented algorithms) have been moved to opencv-contrib repo that is not shipped with the standard binaries and source, the code has to be built. In the following we'll provide the necessary steps to update the optimeyes code in Windows to work with newer versions of the library.

1. Building OpenCV >= 3.0.0 with CMake and Visual Studio: 
follow the steps explained in this stackoverflow reply:
http://stackoverflow.com/questions/37517983/opencv-install-opencv-contrib-on-windows

2. Once the installation of OpenCV is done, proceed to optimeyes:
In my forked repo, I pushed the code I slightly edited to use OpenCV 3:
https://github.com/okbalefthanded/optimeyes
clone the project and run eyeDetect.py

**Comment by LukeAllen** [comment]
Thanks @okbalefthanded. If you want, feel free to make a pull request to README.md to add a link to Windows installation instructions.

**Comment by abk27** [comment]
Thanks @okbalefthanded  and @LukeAllen  . instead of using visual studio ,Is that having another option?
I am using ANACONDA editor and pycham. I have to click using gaze on laptop that's why  I am referring this code @LukeAllen  . Is it possible using this project that click accurately using gaze in particular point? Please tell me.@okbalefthanded  and @LukeAllen  .Its awesome works ,I am totally appreciate with that.Thanks

**Comment by LukeAllen** [comment]
@abk27 with a normal webcam, the results will not be accurate enough to control a mouse cursor precisely. So I think it probably won't work for your purpose. Also, I don't know much about compiling OpenCV on Windows, so I don't think I can help you there.

**Comment by abk27** [comment]
Thanks @LukeAllen .I will update all things after complete my project on window platform.Thanks.
