### ISSUE TITLE
Loading Saved Model

### ISSUE THREAD

**Issue by rl-grimey** [LukeAllen/optimeyes#5]
Hi @adam-jensen!
First off, awesome work so far. 

I'm trying to use your library to predict gaze coordinates using a serialized (trained) model. Your original code has the resultsXY list written to csv. Can we use the .csv (or serialized pickle object) to instantiate a `resultXYpxpy` list, and then add a single frames gaze coordinates to make a prediction?

More specifically, what would be neccesary to do so? Is it just loading the old models crosshair.result (HT, etc?) Let me know if I can clarify anything, I'll submit some code examples when I get time to.

EDIT: To give some context, I'm trying to change my window focus based on which window the gaze is on. I'd like to train a model on startup and store the necessary variables to disk. Then, when the modified eyeDetect.py is called, it loads the variables into file before grabbing a frame, and returning x, y coordinates. I'd then like to use those with a window manager (i3wm) to grab the workspace and focus it.

**Comment by LukeAllen** [comment]
Hey,
It's been a while since I delved into our code, but if I recall, the main objects with persistent state are: 
1) ```eyeDetect.py:virtualpoint```, which holds the original SURF keypoint descriptors and their offsets from the virtual reference point
2) ```eyeDetect.py:HT``` , the transformation matrix which converts (eye pupil offset from virtual ref point) -> (pixel coordinates of gaze). 

So, if the user's head hasn't moved at all, you could restore ```virtualpoint``` and ```HT``` (or, optionally, retrain ```HT``` from the results list). However, over the course of a desktop session, a normal user's head will definitely move (both left/right and closer/farther from the screen). So for your purpose, you'll probably need to add compensation for head movement, as discussed in our paper.

**Comment by ghost** [comment]
what paper? I didn't see any paper. can you pls give me the address to your paper?

**Comment by LukeAllen** [comment]
The paper is the only PDF file in the repo.
